ifeq ($(CONFIG_FPGA_TEST),y)
#obj-y += clk_fpga.o
obj-y += clk_sources.o clk.o clk_cgu.o  clk_cpccr.o  clk_gate.o  clk_pll.o
else
obj-y += clk_sources.o clk.o clk_cgu.o  clk_cpccr.o  clk_gate.o  clk_pll.o
endif
