
CFLAGS_KERNEL	+= -I$(srctree)/arch/mips/xburst2/soc-t40/chip-t40/isvp/Swan
#CFLAGS_KERNEL	+= -I$(srctree)/arch/mips/xburst2/soc-t40/chip-t40/$(CONFIG_PRODUCT_NAME)/$(CONFIG_BOARD_NAME)

obj-y		+= common/
obj-y		+= Swan/
